class Options:
    @staticmethod
    def default() -> Options: ...
    @property
    def resources_dir(self) -> str | None: ...
    @resources_dir.setter
    def resources_dir(self, value: str, /) -> None: ...
    @property
    def dpi(self) -> float: ...
    @dpi.setter
    def dpi(self, value: float, /) -> None: ...
    @property
    def font_family(self) -> str: ...
    @font_family.setter
    def font_family(self, value: str, /) -> None: ...
    @property
    def font_size(self) -> float: ...
    @font_size.setter
    def font_size(self, value: float, /) -> None: ...
    def load_system_fonts(self) -> None: ...
    def load_font_file(self, path: str, /) -> None: ...
    def load_fonts_dir(self, path: str, /) -> None: ...
    def set_serif_family(self, family: str, /) -> None: ...
    def set_sans_serif_family(self, family: str, /) -> None: ...
    def set_cursive_family(self, family: str, /) -> None: ...
    def set_fantasy_family(self, family: str, /) -> None: ...
    def set_monospace_family(self, family: str, /) -> None: ...

class Tree:
    @staticmethod
    def from_str(svg: str, opts: Options, /) -> Tree: ...
    def int_size(self) -> tuple[int, int]: ...
