class Options:
    @staticmethod
    def default() -> Options: ...
    
    @property
    def resources_dir(self) -> str: ...
    
    @resources_dir.setter
    def resources_dir(self, value: str, /) -> None: ...
    
    @property
    def dpi(self) -> float: ...
    
    @dpi.setter
    def dpi(self, value: float, /) -> None: ...

    @property
    def font_family(self) -> str: ...

    @font_family.setter
    def font_family(self, value: str, /) -> None: ...

    @property
    def font_size(self) -> float: ...

    @font_size.setter
    def font_size(self, value: float, /) -> None: ...


class Tree:
    @staticmethod
    def from_str(svg: str, opts: Options, /) -> Tree: ...
    
    def int_size(self) -> tuple[int, int]: ...
